# Generated by Django 5.2 on 2025-04-17 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_engineer_session'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Engineer_Session',
        ),
    ]
