# Generated by Django 5.2 on 2025-04-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_delete_engineer_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
