# Generated by Django 5.2 on 2025-04-18 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
