# Generated by Django 5.2 on 2025-04-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_remove_user_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progresssummary',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='progresssummary',
            name='overall_vote',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='progresssummary',
            unique_together={('team', 'session', 'card')},
        ),
    ]
