# Generated by Django 5.2 on 2025-04-22 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_alter_progresssummary_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresssummary',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.team'),
        ),
    ]
